Content-Type: application/json

{"email":"2022-04-01T08:17:47.484Z@test.com","password":"1234","username":"test","mobile":"010-1234-5678"}

###

get https://localhost:3000/auth

###
post https://localhost:4000/signin
Content-Type: application/json

{"email":"hoyong@codestates.com","password":"password"}